# -*- coding: utf-8 -*-
"""Per-page bilingual config for the pre-render engine.
A page is treated as a product (Product+Offer schema) iff it has an "ebook" block.
Otherwise it is a content page (WebPage schema)."""

def _ebook(img_fr, img_en, url_fr, url_en, pf, pe, cfa, cta_fr, cta_en, af, ae, slug, cf="EUR", ce="USD"):
    return {"img_fr": img_fr, "img_en": img_en, "url_fr": url_fr, "url_en": url_en,
            "price_fr": pf, "price_en": pe, "price_cfa": cfa, "cta_fr": cta_fr, "cta_en": cta_en,
            "amount_fr": af, "cur_fr": cf, "amount_en": ae, "cur_en": ce, "preview_slug": slug}

PAGES = [
  {"src": "pellicules.html", "slug_fr": "pellicules", "slug_en": "dandruff",
   "ebook": _ebook("assets/pellicules.webp", "assets/dandruff.webp", "https://selar.com/pellicules", "https://selar.com/dandruff",
                   "8€", "$9", "≈ 5 000 FCFA", "Retrouver un cuir chevelu sain →", "Get a healthy scalp →", "8.00", "9.00", "pellicules"),
   "name_fr": "Adieu Pellicules", "name_en": "Goodbye Dandruff", "cat_fr": "Ebooks", "cat_en": "Ebooks",
   "title_fr": "Adieu Pellicules — Guide Cuir Chevelu Cheveux Crépus Type 4 | Schicgirl",
   "title_en": "Goodbye Dandruff — Type 4 Coily Hair Scalp Guide | Schicgirl",
   "desc_fr": "Comprends et élimine les pellicules sur cheveux crépus Type 4 : les 6 types, diagnostic, routines, ingrédients actifs, recettes DIY et défi 30 jours.",
   "desc_en": "Understand and clear dandruff on Type 4 coily hair: the 6 types, diagnosis, routines, active ingredients, DIY recipes and a 30-day challenge."},

  {"src": "hydratee.html", "slug_fr": "hydratation-cheveux-crepus", "slug_en": "hydrate-type-4-hair",
   "ebook": _ebook("assets/hydratee.webp", "assets/hydrated.webp", "https://selar.com/hydratee", "https://selar.com/hydrated",
                   "17€", "$18", "≈ 11 000 FCFA", "Obtenir Hydratée →", "Get Hydrated →", "17.00", "18.00", "hydratee"),
   "name_fr": "Hydratée", "name_en": "Hydrated", "cat_fr": "Ebooks", "cat_en": "Ebooks",
   "title_fr": "Hydratée — Guide Hydratation Cheveux Crépus Type 4 (4A 4B 4C) | Schicgirl",
   "title_en": "Hydrated — The Type 4 Coily Hair Moisture Guide (4A 4B 4C) | Schicgirl",
   "desc_fr": "Le système complet pour hydrater durablement les cheveux crépus Type 4 (4A 4B 4C) : méthode LOC/LCO, porosité, recettes et routine.",
   "desc_en": "The complete system to deeply hydrate Type 4 coily hair (4A 4B 4C): the LOC/LCO method, porosity, recipes and a lasting routine."},

  {"src": "pousse.html", "slug_fr": "faire-pousser-cheveux-crepus", "slug_en": "grow-type-4-hair",
   "ebook": _ebook("assets/pousse.webp", "assets/grow.webp", "https://selar.com/pousse", "https://selar.com/grow-hair",
                   "14€", "$15", "≈ 9 000 FCFA", "Commencer ma pousse →", "Start my growth →", "14.00", "15.00", "pousse"),
   "name_fr": "Pousse Maximale", "name_en": "Maximum Growth", "cat_fr": "Ebooks", "cat_en": "Ebooks",
   "title_fr": "Pousse Maximale — Faire Pousser ses Cheveux Crépus Sans Casse | Schicgirl",
   "title_en": "Maximum Growth — Grow Type 4 Coily Hair Without Breakage | Schicgirl",
   "desc_fr": "Le système complet de pousse pour cheveux crépus Type 4 : rétention de longueur, cuir chevelu, équilibre protéines/hydratation et routine.",
   "desc_en": "The complete growth system for Type 4 coily hair: length retention, scalp care, the protein/moisture balance and a clear routine."},

  {"src": "coiffures.html", "slug_fr": "coiffures-protectrices", "slug_en": "protective-styles",
   "ebook": _ebook("assets/coiffures-fr.webp", "assets/hair-styles.webp", "https://selar.com/coiffures-protectrices", "https://selar.com/hair-styles",
                   "5€", "$6", "≈ 3 500 FCFA", "Protéger mes cheveux →", "Protect my hair →", "5.00", "6.00", "coiffures"),
   "name_fr": "Coiffures Protectrices", "name_en": "Protective Styles", "cat_fr": "Ebooks", "cat_en": "Ebooks",
   "title_fr": "Coiffures Protectrices Cheveux Crépus Type 4 — Sans Casse | Schicgirl",
   "title_en": "Protective Styles for Type 4 Coily Hair — No Breakage | Schicgirl",
   "desc_fr": "Réussir ses coiffures protectrices sans sécheresse ni casse sur cheveux crépus Type 4 : le cycle avant/pendant/après, choix des styles et entretien.",
   "desc_en": "Master protective styles on Type 4 coily hair without dryness or breakage: the before/during/after cycle, choosing styles and upkeep."},

  {"src": "stop-cheveux-secs.html", "slug_fr": "cheveux-secs", "slug_en": "dry-hair",
   "ebook": _ebook("assets/stop-cheveux-secs.webp", "assets/stop-dry-hair.webp", "https://selar.com/stop-cheveux-secs", "https://selar.com/stop-dry-hair",
                   "5€", "$6", "≈ 3 500 FCFA", "Commencer pour 5€ →", "Start for $6 →", "5.00", "6.00", "stop-cheveux-secs"),
   "name_fr": "Stop aux Cheveux Secs", "name_en": "Stop Dry Hair", "cat_fr": "Ebooks", "cat_en": "Ebooks",
   "title_fr": "Stop aux Cheveux Secs — En Finir avec la Sécheresse Type 4 | Schicgirl",
   "title_en": "Stop Dry Hair — End Type 4 Coily Dryness for Good | Schicgirl",
   "desc_fr": "Le guide express pour comprendre pourquoi tes cheveux crépus sèchent et l'arrêter dès aujourd'hui. Système simple et fiches prêtes à l'emploi.",
   "desc_en": "The express guide to understand why your coily hair dries out and stop it today. A simple system and ready-to-use sheets for Type 4."},

  {"src": "transition.html", "slug_fr": "transition-capillaire", "slug_en": "hair-transition",
   "ebook": _ebook("assets/transition-fr.webp", "assets/transition-en.webp", "https://selar.com/transition-fr", "https://selar.com/transition-en",
                   "7€", "$7", "≈ 4 500 FCFA", "Réussir ma transition →", "Nail my transition →", "7.00", "7.00", "transition"),
   "name_fr": "Cheveux en Transition", "name_en": "Hair in Transition", "cat_fr": "Ebooks", "cat_en": "Ebooks",
   "title_fr": "Transition Capillaire — Du Défrisé au Naturel Sans Casse | Schicgirl",
   "title_en": "Hair Transition — From Relaxed to Natural Without Breakage | Schicgirl",
   "desc_fr": "Réussir sa transition du défrisé au naturel sans big chop forcé : gérer deux textures, éviter la casse, plan 90 jours et coupes.",
   "desc_en": "Go from relaxed to natural without a forced big chop: manage two textures, avoid breakage, a 90-day plan and trims."},

  {"src": "pack-complet.html", "slug_fr": "pack-complet", "slug_en": "complete-pack",
   "ebook": _ebook("assets/all-ebook.webp", "assets/all-ebook.webp", "https://selar.com/pack-complet", "https://selar.com/complete-pack",
                   "59€", "$65", "≈ 39 000 FCFA", "Obtenir le système complet →", "Get the complete system →", "59.00", "65.00", "pack-complet"),
   "name_fr": "Le Système Complet", "name_en": "The Complete System", "cat_fr": "Ebooks", "cat_en": "Ebooks",
   "title_fr": "Le Système Complet — Les 6 Guides Cheveux Crépus Type 4 | Schicgirl",
   "title_en": "The Complete System — All 6 Type 4 Coily Hair Guides | Schicgirl",
   "desc_fr": "Tous les guides Schicgirl en un seul pack : hydratation, pousse, pellicules, coiffures protectrices, cheveux secs et transition — la méthode Type 4 complète.",
   "desc_en": "Every Schicgirl guide in one pack: hydration, growth, dandruff, protective styles, dry hair and transition — the full Type 4 method."},

  {"src": "planner.html", "slug_fr": "planner", "slug_en": "planner",
   "ebook": _ebook("assets/planner-cover-fr.png", "assets/planner-cover-en.png", "https://selar.com/studio-planner", "https://selar.com/studio-planner",
                   "9€", "$10", "≈ 6 000 FCFA", "Obtenir le Studio →", "Get the Studio →", "9.00", "10.00", "planner"),
   "name_fr": "Le Studio · Planner Type 4", "name_en": "The Studio · Type 4 Planner", "cat_fr": "Le Studio", "cat_en": "The Studio",
   "title_fr": "Le Studio — Planificateur & Cahier Routine Cheveux Crépus Type 4 | Schicgirl",
   "title_en": "The Studio — Type 4 Coily Hair Routine Planner & Workbook | Schicgirl",
   "desc_fr": "Le planificateur-coaching Type 4 : diagnostic, routine sur mesure, calendrier et suivi. Une app interactive + un cahier PDF de 36 pages.",
   "desc_en": "The Type 4 coaching planner: diagnosis, custom routine, calendar and tracking. An interactive app plus a 36-page PDF workbook."},

  {"src": "why-nothing-works.html", "slug_fr": "pourquoi-rien-ne-fonctionne", "slug_en": "why-nothing-works",
   "ebook": _ebook("assets/why-nothing-works-fr.webp", "assets/why-nothing-works-en.webp", "https://selar.com/Pourquoi_Rien_Ne_Fonctionne", "https://selar.com/Why_Nothing_Works",
                   "12€", "$13", "≈ 8 000 FCFA", "Obtenir le guide →", "Get the guide →", "12.00", "13.00", "why-nothing-works"),
   "name_fr": "Pourquoi Rien Ne Fonctionne", "name_en": "Why Nothing Works", "cat_fr": "Ebooks", "cat_en": "Ebooks",
   "title_fr": "Pourquoi Rien Ne Fonctionne — Le Système Diagnostic Cheveux Crépus Type 4 | Schicgirl",
   "title_en": "Why Nothing Works — The Diagnosis-First System for Type 4 Coily Hair | Schicgirl",
   "desc_fr": "Arrête d'acheter au hasard : le système diagnostic-first pour cheveux crépus Type 4 (4A 4B 4C). Porosité, densité, cuir chevelu, playbooks 4A/4B/4C, plan 90 jours.",
   "desc_en": "Stop buying at random: the diagnosis-first system for Type 4 coily hair (4A 4B 4C). Porosity, density, scalp, 4A/4B/4C playbooks, a 90-day plan."},

  {"src": "creer-ma-routine.html", "slug_fr": "creer-ma-routine-capillaire", "slug_en": "build-my-hair-routine",
   "ebook": _ebook("assets/creer-ma-routine-fr.webp", "assets/creer-ma-routine-en.webp", "https://selar.com/Comment_creer_ma_routine_capillaire", "https://selar.com/How_to_Build_My_Hair_Routine",
                   "19€", "$20", "≈ 12 500 FCFA", "Créer ma routine →", "Build my routine →", "19.00", "20.00", "creer-ma-routine"),
   "name_fr": "Comment créer ma routine capillaire", "name_en": "How to Build My Hair Routine", "cat_fr": "Ebooks", "cat_en": "Ebooks",
   "title_fr": "Comment Créer Ma Routine Capillaire — Guide Routine Cheveux Crépus Type 4 | Schicgirl",
   "title_en": "How to Build My Hair Routine — The Type 4 Coily Hair Routine Guide | Schicgirl",
   "desc_fr": "Crée étape par étape la routine cheveux crépus Type 4 qui marche pour toi : nettoyage, hydratation, scellage, wash day, semaine et routine de nuit.",
   "desc_en": "Build, step by step, the Type 4 coily hair routine that works for you: cleanse, moisturize, seal, wash day, weekly rhythm and night routine."},

  {"src": "recettes.html", "slug_fr": "recettes-cheveux-crepus", "slug_en": "type-4-hair-recipes",
   "ebook": _ebook("assets/recettes-fr.webp", "assets/recettes-en.webp", "https://selar.com/recettes_FR", "https://selar.com/recipes_EN",
                   "9€", "$10", "≈ 6 000 FCFA", "Obtenir mes recettes →", "Get my recipes →", "9.00", "10.00", "recettes"),
   "name_fr": "Mes Recettes Type 4", "name_en": "My Type 4 Recipe Book", "cat_fr": "Ebooks", "cat_en": "Ebooks",
   "title_fr": "Mes Recettes Type 4 — 12 Soins Maison Cheveux Crépus | Schicgirl",
   "title_en": "My Type 4 Recipe Book — 12 Homemade Treatments for Coily Hair | Schicgirl",
   "desc_fr": "12 recettes maison pour cheveux crépus Type 4 : masques profonds, spritz hydratant, pré-poo, rhassoul — quantités exactes et adaptations porosité.",
   "desc_en": "12 homemade recipes for Type 4 coily hair: deep masks, hydrating spritz, pre-poo, rhassoul — exact amounts and porosity adaptations."},

  {"src": "pack-suivi.html", "slug_fr": "pack-suivi-type-4", "slug_en": "type-4-tracker-pack",
   "ebook": _ebook("assets/pack-suivi-fr.webp", "assets/pack-suivi-en.webp", "https://selar.com/Pack_Suivi_Type4_FR", "https://selar.com/Type4_Tracker_Pack_EN",
                   "5€", "$6", "≈ 3 500 FCFA", "Obtenir le pack →", "Get the pack →", "5.00", "6.00", "pack-suivi"),
   "name_fr": "Le Pack Suivi Type 4", "name_en": "The Type 4 Tracker Pack", "cat_fr": "Ebooks", "cat_en": "Ebooks",
   "title_fr": "Le Pack Suivi Type 4 — 4 Fiches à Imprimer Cheveux Crépus | Schicgirl",
   "title_en": "The Type 4 Tracker Pack — 4 Printable Hair Tracker Sheets | Schicgirl",
   "desc_fr": "4 fiches de suivi imprimables pour cheveux crépus Type 4 : jour de lavage, pousse 12 mois, inventaire produits, équilibre protéines-hydratation.",
   "desc_en": "4 printable tracker sheets for Type 4 coily hair: wash day, 12-month growth log, product inventory, protein-moisture balance."},

  {"src": "le-studio-premium.html", "slug_fr": "le-studio-premium", "slug_en": "premium-studio",
   "ebook": _ebook("assets/studio-premium-fr.webp", "assets/studio-premium-en.webp", "https://selar.com/studio_premium", "https://selar.com/studio_premium",
                   "29€", "$32", "≈ 19 000 FCFA", "Débloquer mon Studio Premium →", "Unlock my Premium Studio →", "29.00", "32.00", "studio-premium"),
   "name_fr": "Le Studio Premium", "name_en": "The Premium Studio", "cat_fr": "Ebooks", "cat_en": "Ebooks",
   "title_fr": "Le Studio Premium — L'App Type 4 + 3 Guides Complets en Cours | Schicgirl",
   "title_en": "The Premium Studio — The Type 4 App + 3 Full Guides as Courses | Schicgirl",
   "desc_fr": "L'app interactive Type 4 + les 3 guides Schicgirl en cours interactifs : 76 leçons FR/EN, progression validée leçon par leçon, sauvegarde cloud, accès à vie.",
   "desc_en": "The interactive Type 4 app + the 3 Schicgirl guides as interactive courses: 76 lessons FR/EN, lesson-by-lesson validation, cloud backup, lifetime access."},

  {"src": "about.html", "slug_fr": "a-propos", "slug_en": "about",
   "name_fr": "À Propos", "name_en": "About", "cat_fr": "À Propos", "cat_en": "About",
   "title_fr": "À Propos de Schicgirl — Cheveux Crépus Type 4 Simplifiés | Schicgirl",
   "title_en": "About Schicgirl — Type 4 Natural Hair Made Simple | Schicgirl",
   "desc_fr": "Schicgirl aide les femmes aux cheveux crépus Type 4 à comprendre la sécheresse, construire une routine simple et choisir des produits fiables.",
   "desc_en": "Schicgirl helps women with curly, coily and kinky Type 4 hair understand dryness, build a simple routine and choose trusted products."},

  {"src": "blog.html", "slug_fr": "blog", "slug_en": "blog",
   "name_fr": "Blog", "name_en": "Blog", "cat_fr": "Blog", "cat_en": "Blog",
   "title_fr": "Blog Schicgirl — Conseils Cheveux Crépus Type 4 | Schicgirl",
   "title_en": "Schicgirl Blog — Natural Hair Tips for Type 4 Curls & Coils | Schicgirl",
   "desc_fr": "Des conseils experts et clairs pour cheveux crépus Type 4 : pourquoi ils sont secs, la porosité, le wash day parfait, les routines.",
   "desc_en": "Clear, expert natural hair advice for Type 4 curls and coils: why coily hair is dry, porosity, the perfect wash day and routines."},

  {"src": "contact.html", "slug_fr": "contact", "slug_en": "contact",
   "name_fr": "Contact", "name_en": "Contact", "cat_fr": "Contact", "cat_en": "Contact",
   "title_fr": "Contact Schicgirl — Questions, Collabs & Support | Schicgirl",
   "title_en": "Contact Schicgirl — Questions, Collabs & Support | Schicgirl",
   "desc_fr": "Contacte Schicgirl — questions sur ta routine cheveux naturels, les guides, collaborations ou support. Email, Facebook et réseaux.",
   "desc_en": "Get in touch with Schicgirl — questions about your natural hair routine, the guides, collaborations or support. Email, Facebook and socials."},

  {"src": "privacy-policy.html", "slug_fr": "confidentialite", "slug_en": "privacy-policy",
   "name_fr": "Politique de Confidentialité", "name_en": "Privacy Policy", "cat_fr": "Légal", "cat_en": "Legal",
   "title_fr": "Politique de Confidentialité — Schicgirl",
   "title_en": "Privacy Policy — Schicgirl",
   "desc_fr": "Comment Schicgirl collecte, utilise et protège tes données : cookies, publicité Google AdSense, analytics, inscriptions email et tes droits.",
   "desc_en": "How Schicgirl collects, uses and protects your data: cookies, Google AdSense advertising, analytics, email signups and your rights."},

  {"src": "terms.html", "slug_fr": "conditions", "slug_en": "terms",
   "name_fr": "Conditions d'Utilisation", "name_en": "Terms of Service", "cat_fr": "Légal", "cat_en": "Legal",
   "title_fr": "Conditions d'Utilisation — Schicgirl",
   "title_en": "Terms of Service — Schicgirl",
   "desc_fr": "Les conditions d'utilisation de Schicgirl : produits numériques et ebooks, remboursements, propriété intellectuelle, affiliation et avertissement santé.",
   "desc_en": "The terms for using Schicgirl: digital products and ebooks, refunds, intellectual property, affiliate disclosure and the health disclaimer."},

  # keep_attrs: these pages keep an in-place language toggle + JS-rendered lists,
  # so both data-fr/data-en attributes are retained (visible text is still baked per language).
  {"src": "products.html", "slug_fr": "produits", "slug_en": "products", "keep_attrs": True,
   "name_fr": "Produits", "name_en": "Products", "cat_fr": "Produits", "cat_en": "Products",
   "title_fr": "Produits Cheveux Naturels par Porosité — Sélection Amazon | Schicgirl",
   "title_en": "Natural Hair Products by Porosity — Amazon Finds | Schicgirl",
   "desc_fr": "La sélection Amazon de Schicgirl pour cheveux crépus Type 4, triée par porosité, avec une bibliothèque d'ingrédients DIY et un quiz de porosité.",
   "desc_en": "Schicgirl's curated Amazon picks for Type 4 coily hair, sorted by porosity, with a DIY ingredient library and a 60-second porosity quiz."},

  {"src": "toolkit-landing.html", "slug_fr": "kit-gratuit", "slug_en": "free-kit", "keep_attrs": True,
   "name_fr": "Le Kit Type 4 (Gratuit)", "name_en": "The Free Type 4 Kit", "cat_fr": "Gratuit", "cat_en": "Free",
   "title_fr": "Le Kit Type 4 Gratuit — 4 Guides Cheveux Crépus | Schicgirl",
   "title_en": "The Free Type 4 Kit — 4 Coily Hair Guides | Schicgirl",
   "desc_fr": "Recevez gratuitement le Kit Type 4 : 4 guides pour comprendre pourquoi vos cheveux crépus sont secs, votre porosité et votre jour de lavage.",
   "desc_en": "Get the free Type 4 Kit: 4 guides to understand why your coily hair is dry, your porosity and your wash day — step by step."},
]
